In [34]:
import torch
import numpy as np
import random

In [17]:
torch.__version__

'2.10.0'

# Tensors

In [18]:
tensor = torch.tensor(1)
tensor

tensor(1)

In [19]:
# dimension of tensor
tensor.ndim

0

In [20]:
# vector - tensor with one dimension
tensor1 = torch.tensor([1,2,3,4,5])
tensor1

tensor([1, 2, 3, 4, 5])

In [21]:
tensor1.ndim

1

In [22]:
# matrix - tensor with two dimensions
tensor2 = torch.tensor([[0,1,2], 
                        [2,3,4]])
tensor2

tensor([[0, 1, 2],
        [2, 3, 4]])

In [23]:
# Dimension and shape of a tensor
print(f"Vector:\n{tensor1}\tNo. of Dimensions: {tensor1.ndim}\tShape: {tensor1.shape}\n")
print(f"Vector:\n{tensor2}\tNo. of Dimensions: {tensor2.ndim}\tShape: {tensor2.shape}\n")

Vector:
tensor([1, 2, 3, 4, 5])	No. of Dimensions: 1	Shape: torch.Size([5])

Vector:
tensor([[0, 1, 2],
        [2, 3, 4]])	No. of Dimensions: 2	Shape: torch.Size([2, 3])



In [24]:
# Alternate ways - Create a zero tensor
size = (3, 4, 6)
tensor3 = torch.empty(size)
tensor3


tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [25]:
# initialise a random tensor

random_tensor = torch.rand(size)
random_tensor

tensor([[[0.0277, 0.1061, 0.9081, 0.5538, 0.9873, 0.9134],
         [0.5116, 0.5920, 0.8738, 0.4499, 0.3077, 0.6005],
         [0.2530, 0.3953, 0.0021, 0.3388, 0.5500, 0.3564],
         [0.5156, 0.0218, 0.4743, 0.2095, 0.9908, 0.0913]],

        [[0.0432, 0.3958, 0.1178, 0.9065, 0.7950, 0.8022],
         [0.0831, 0.4214, 0.0872, 0.6690, 0.1035, 0.4088],
         [0.7791, 0.8500, 0.1027, 0.5223, 0.1314, 0.9270],
         [0.7401, 0.3948, 0.7744, 0.7570, 0.0988, 0.8338]],

        [[0.1084, 0.6586, 0.5603, 0.0598, 0.6595, 0.1894],
         [0.4376, 0.4499, 0.1891, 0.1261, 0.3719, 0.3065],
         [0.4007, 0.6812, 0.5063, 0.9572, 0.5971, 0.2770],
         [0.7308, 0.5704, 0.1481, 0.8672, 0.9143, 0.2216]]])

In [26]:
# zero tensor and ones tensor
zero_tensor = torch.zeros(size)
ones_tensor = torch.ones(size)

zero_tensor, ones_tensor

(tensor([[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1.]]]))

In [27]:
# check datatype of the tensor - default is float32 for any tensor
tensor = torch.rand(1, 2)
print(tensor)
tensor.dtype


tensor([[0.7599, 0.5691]])


torch.float32

In [28]:
# create a tensor with specific datatype
tensor = torch.tensor([1,2,3,4], dtype=torch.float16)
print(tensor)
tensor.dtype

tensor([1., 2., 3., 4.], dtype=torch.float16)


torch.float16

In [31]:
# change the datatype of a tensor
tensor_another = tensor.type(torch.double)
tensor_another.dtype

torch.float64

In [ ]:
# convert numpy array to a tensor
example = np.array([[random.randint(1, 9) for _ in range(10)], 
                    [random.randint(1,9) for _ in range(10)]])

# from_numpy shares the same memory as the example
tensor_one = torch.from_numpy(example)

# changes done in the example array does not reflect in this tensor
tensor_two = torch.tensor(example)

example, tensor_one, tensor_two


(array([[7, 5, 1, 2, 8, 8, 3, 4, 2, 1],
        [4, 2, 5, 7, 9, 3, 5, 7, 1, 4]]),
 tensor([[7, 5, 1, 2, 8, 8, 3, 4, 2, 1],
         [4, 2, 5, 7, 9, 3, 5, 7, 1, 4]]),
 tensor([[7, 5, 1, 2, 8, 8, 3, 4, 2, 1],
         [4, 2, 5, 7, 9, 3, 5, 7, 1, 4]]))

In [43]:
# demonstarting the difference between the two methods
example *= 3

example, tensor_one, tensor_two


(array([[21, 15,  3,  6, 24, 24,  9, 12,  6,  3],
        [12,  6, 15, 21, 27,  9, 15, 21,  3, 12]]),
 tensor([[21, 15,  3,  6, 24, 24,  9, 12,  6,  3],
         [12,  6, 15, 21, 27,  9, 15, 21,  3, 12]]),
 tensor([[7, 5, 1, 2, 8, 8, 3, 4, 2, 1],
         [4, 2, 5, 7, 9, 3, 5, 7, 1, 4]]))

In [44]:
## creating a tensor using another tensor
tensor_three = torch.ones_like(tensor_one)
tensor_three

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
# Device Configuration 

# check for cuda
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print(device)

cpu


In [46]:
# send tensors to specific device
tensor_four = torch.ones(3,3).to(device)

tensor_five = torch.zeros(3,7, device=device)


In [50]:
# accessing element from a tensor
print(tensor2)
print(f"Dim: {tensor2.dim()}")
print(f"Size: {tensor2.size()}")

# print array in the first dim
print(tensor2[1])

# print element using specific index
print(tensor2[0][2])


tensor([[0, 1, 2],
        [2, 3, 4]])
Dim: 2
Size: torch.Size([2, 3])
tensor([2, 3, 4])
tensor(2)


In [52]:
# Slicing follows numpy rules
print(tensor2[:, 2])

print(tensor2[0, :])


tensor([2, 4])
tensor([0, 1, 2])


## Basic Tensor Operations

In [ ]:
tensor_one = torch.tensor([10, 20, 30])
tensor_two = torch.tensor([10, 10, 10])

In [54]:
# Element wise arithmetic operations

# Addition
print(tensor_one + tensor_two)

# Subtraction
print(tensor_one - tensor_two)

# Multiplication
print(tensor_one * tensor_two)

# Division
print(tensor_one / tensor_two)


tensor([[28, 20,  4,  8, 32, 32, 12, 16,  8,  4],
        [16,  8, 20, 28, 36, 12, 20, 28,  4, 16]])
tensor([[14, 10,  2,  4, 16, 16,  6,  8,  4,  2],
        [ 8,  4, 10, 14, 18,  6, 10, 14,  2,  8]])
tensor([[147,  75,   3,  12, 192, 192,  27,  48,  12,   3],
        [ 48,  12,  75, 147, 243,  27,  75, 147,   3,  48]])
tensor([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])


In [60]:
# random tensors (again)
random_tensor = torch.randint(1,9, size=(4,6))
random_tensor

tensor([[2, 1, 5, 7, 1, 3],
        [5, 8, 1, 7, 7, 7],
        [5, 2, 6, 4, 3, 2],
        [6, 7, 8, 2, 7, 6]])

In [61]:
# reshape tensors 

y = random_tensor.view(24)
z = random_tensor.view(-1, 2)

print(y, z)

tensor([2, 1, 5, 7, 1, 3, 5, 8, 1, 7, 7, 7, 5, 2, 6, 4, 3, 2, 6, 7, 8, 2, 7, 6]) tensor([[2, 1],
        [5, 7],
        [1, 3],
        [5, 8],
        [1, 7],
        [7, 7],
        [5, 2],
        [6, 4],
        [3, 2],
        [6, 7],
        [8, 2],
        [7, 6]])


In [65]:
# create a tensor by specifying a range
tensor_a = torch.arange(24)
tensor_a = tensor_a.reshape(4,6)
tensor_a

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

In [69]:
# concatenate two arrays
concat = torch.cat((random_tensor, tensor_a), dim=0)
concat

tensor([[ 2,  1,  5,  7,  1,  3],
        [ 5,  8,  1,  7,  7,  7],
        [ 5,  2,  6,  4,  3,  2],
        [ 6,  7,  8,  2,  7,  6],
        [ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

## Reduction Operations

In [70]:
concat.sum()

tensor(388)