In [1]:
corpus = ''' 
I absolutely love this laptop. The battery lasts all day and the display is stunning.

The phone arrived with a cracked screen. Customer support replaced it quickly.

Average product. It works as expected but feels overpriced.

The headphones have amazing sound quality, but the ear cushions become uncomfortable after an hour.

The keyboard feels premium and the keys are responsive.

This camera produces sharp images even in low light.

The smartwatch stopped working after just two weeks.

The charger heats up more than I expected.

Excellent value for money. Highly recommended.

The packaging was damaged, but the product itself was fine.
'''

In [2]:
from transformers import pipeline

# Text gen using pre-defined pipeline
pipe = pipeline("text-generation", model="openai-community/gpt2")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [3]:
prompt = "What is machine learning?"
output = pipe(prompt)

print(output)

print(output[0]['generated_text'])

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.


[{'generated_text': 'What is machine learning?\n\nMachine learning is an algorithm that can understand your information. It can learn about you from your actions and from what you said.\n\nMachine learning is a combination of machine learning and computer vision that allows you to see your information without having to read it.\n\nIt can also see your thoughts, feelings and actions.\n\nThese are all skills that people can learn to use in everyday life.\n\nThis is a great example of how machine learning can help you find things that you need to learn.\n\nWhat is it like to make a decision?\n\nIt\'s easy to make a decision. It\'s like making a decision with your brain. You start to find things that you like that you don\'t like.\n\nYou may think, "I\'m going to go shopping. I\'ve never been to a store. I\'m going to go to a doctor\'s appointment. I\'m going to the gym. I\'m going to read a book." You\'re like, "I\'m not going to go to a doctor\'s appointment." You\'re like, "I\'m going t

In [4]:
from transformers import AutoTokenizer, AutoModelForCausalLM

# manual text gen using model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("openai-community/gpt2")
model = AutoModelForCausalLM.from_pretrained("openai-community/gpt2")

print(model)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)


In [5]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('gpt2')

print(tokenizer)

GPT2Tokenizer(name_or_path='gpt2', vocab_size=50257, model_max_length=1024, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
})


In [6]:
# sub-word level tokenization
word = "unbelievable"
input_ids = tokenizer(word, return_tensors='pt')['input_ids']

print(input_ids)

for token_id in input_ids[0]: 
    print(tokenizer.decode(token_id))

tensor([[  403,  6667, 11203,   540]])
un
bel
iev
able


In [7]:
word = "heterosexuality"
input_ids = tokenizer(word, return_tensors="pt")['input_ids']

print(input_ids)

for token_id in input_ids[0]: 
    print(tokenizer.decode(token_id))

tensor([[43332,  8542,   414]])
heter
osexual
ity


In [8]:
word = "pneumonoultramicroscopicsilicovolcanoconiosis"
input_ids = tokenizer(word, return_tensors="pt")['input_ids']

print(input_ids)
print("Number of Tokens: ", len(input_ids[0]))
for token_id in input_ids[0]: 
    print(tokenizer.decode(token_id))

tensor([[   79, 25668,   261, 25955,   859,  2500,  1416,   404,   873, 41896,
           709,   349,  5171, 36221, 42960]])
Number of Tokens:  15
p
neum
on
oult
ram
icro
sc
op
ics
ilic
ov
ol
can
ocon
iosis


In [9]:
sentence = "antidisestablishmentarianism is what exactly?"

input_ids = tokenizer(sentence, return_tensors="pt")["input_ids"]
print(input_ids)

for token_id in input_ids.squeeze(): 
    print(tokenizer.decode(token_id))

tensor([[  415, 29207, 44390,  3699,  1042,   318,   644,  3446,    30]])
ant
idis
establishment
arian
ism
 is
 what
 exactly
?


In [10]:
from transformers import AutoModelForCausalLM

gpt2 = AutoModelForCausalLM.from_pretrained("gpt2")
print(gpt2)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)


In [24]:
import torch
import torch.nn.functional as F

# predict the next word
sentence = "I like machine learning to be able to do"

token_ids = tokenizer(sentence, return_tensors="pt")['input_ids']
outputs = gpt2(token_ids).logits[0, -1]
final_logits = torch.topk(outputs, 10) # sampling using topk

for index in final_logits.indices: 
    print(tokenizer.decode(index))

 things
 a
 something
 that
 the
 more
 what
 this
 some
 it


In [ ]:
sentence = "I learn machine learning to"
n = 100
while n > 0: 
    token_ids = tokenizer(sentence, return_tensors="pt")["input_ids"]
    outputs = gpt2(token_ids).logits[0, -1]
    token = tokenizer.decode(outputs.argmax())
    sentence += token
    print(n, sentence, "\n")
    n -= 1

100 I learn machine learning to be 

99 I learn machine learning to be a 

98 I learn machine learning to be a lot 

97 I learn machine learning to be a lot more 

96 I learn machine learning to be a lot more complex 

95 I learn machine learning to be a lot more complex than 

94 I learn machine learning to be a lot more complex than I 

93 I learn machine learning to be a lot more complex than I thought 

92 I learn machine learning to be a lot more complex than I thought it 

91 I learn machine learning to be a lot more complex than I thought it would 

90 I learn machine learning to be a lot more complex than I thought it would be 

89 I learn machine learning to be a lot more complex than I thought it would be. 

88 I learn machine learning to be a lot more complex than I thought it would be. I 

87 I learn machine learning to be a lot more complex than I thought it would be. I'm 

86 I learn machine learning to be a lot more complex than I thought it would be. I'm not 

85 I lear

In [ ]:
torch.softmax(final_logits.values, dim=0).sum() # softmax alwyas sums upto 1

tensor(1., grad_fn=<SumBackward0>)

In [ ]:
# different sampling strategies
def greedy_decode(logits): 
    '''Return token index with maximum probability'''
    return torch.argmax(logits, dim=-1)

tokenizer.decode(greedy_decode(outputs))

def top_k_sampling(logits, k=50): 
    '''Keeps only top-k logits, normalize them into probabilities using softmax, then sample one token from the filtered distribution'''

    values, indices = torch.topk(logits, k)
    probs = F.softmax(values, dim=-1)
    sampled = torch.multinomial(probs, 1)
    return indices[sampled]

def top_p_sampling(logits, p=0.9): 
    """ 
    Sort tokens by probability, keep smallest number who cumulative probability exceeds threshold p, then sample one token.
    """

    sorted_logits, sorted_indices = torch.sort(logits, decending=True)
    sorted_probs = F.softmax(sorted_logits, dim=-1)
    cumulative_probs = sorted_probs.cumsum(dim=-1)

    # Mask token outside nucleus
    mask = cumulative_probs > p
    sorted_logits[mask] = float("-inf")


In [43]:
tokenizer.decode(top_k_sampling(outputs))

' that'