In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# 0th Dimensional tensor
tensor_zero_d = tf.constant(4, dtype='int8')
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int8)


In [3]:
# 1-D tensor
tensor_one_d = tf.constant([2, 0 , -3], dtype='int8')
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int8)


In [4]:
# 2-D tensor
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -1], 
    [1, 5, 6], 
    [2,3, 8]
])

print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [5]:
# 3-D tensor 
cube = tf.constant([
    [
        [1, 2, 3],  # Plane 1, Row 1
        [4, 5, 6],  # Plane 1, Row 2
        [7, 8, 9]   # Plane 1, Row 3
    ],
    [
        [10, 11, 12], # Plane 2, Row 1
        [13, 14, 15], # Plane 2, Row 2
        [16, 17, 18]  # Plane 2, Row 3
    ],
    [
        [19, 20, 21], # Plane 3, Row 1
        [22, 23, 24], # Plane 3, Row 2
        [25, 26, 27]  # Plane 3, Row 3
    ]
])
print(cube)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]], shape=(3, 3, 3), dtype=int32)


In [6]:
# print the dimensions of the tensor
print(cube.shape)

# print number of dimensions in the tensor
print(cube.ndim)

(3, 3, 3)
3


In [7]:
four_d = tf.constant([
    # Cube 1
    [
        [
            [1, 2],
            [3, 4]
        ],
        [
            [5, 6],
            [7, 8]
        ]
    ],
    # Cube 2
    [
        [
            [9, 10],
            [11, 12]
        ],
        [
            [13, 14],
            [15, 16]
        ]
    ]
])
print(four_d)

tf.Tensor(
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]], shape=(2, 2, 2, 2), dtype=int32)


In [8]:
# Type casting tensors

# float type tensor
tensor_one_d = tf.constant([2.7, 0 , -3.02, 6, 7, 8], dtype=tf.float32)
casted_tensor = tf.cast(tensor_one_d,  dtype=tf.int8)
check_dtype_bool = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor)
print(check_dtype_bool)

tf.Tensor([ 2.7   0.   -3.02  6.    7.    8.  ], shape=(6,), dtype=float32)
tf.Tensor([ 2  0 -3  6  7  8], shape=(6,), dtype=int8)
tf.Tensor([ True False  True  True  True  True], shape=(6,), dtype=bool)


In [9]:
# boolean tensor
tensor_bool = tf.constant([True, True, False, True])
print(tensor_bool)

tf.Tensor([ True  True False  True], shape=(4,), dtype=bool)


In [10]:
# String tensor
tensor_string = tf.constant(['hello', 'world', 'hi', 'greetings'])
tensor_string

<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'hello', b'world', b'hi', b'greetings'], dtype=object)>

In [11]:
# convert numpy array into a tensor
np_array = np.array([1,2,4])
print(np_array)

converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

[1 2 4]
tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [12]:
# construct identity matrix
identity = tf.eye(
    num_rows = 3, 
    num_columns = 3, 
    batch_shape = [2, ], # adds dimensions above rows and columns
    dtype = tf.int8
)

print(identity)

print(3 * identity)

tf.Tensor(
[[[1 0 0]
  [0 1 0]
  [0 0 1]]

 [[1 0 0]
  [0 1 0]
  [0 0 1]]], shape=(2, 3, 3), dtype=int8)
tf.Tensor(
[[[3 0 0]
  [0 3 0]
  [0 0 3]]

 [[3 0 0]
  [0 3 0]
  [0 0 3]]], shape=(2, 3, 3), dtype=int8)


In [13]:
# create a tensor filled with a scalar value

filled = tf.fill([2,3], 69)
print(filled)

tf.Tensor(
[[69 69 69]
 [69 69 69]], shape=(2, 3), dtype=int32)


In [14]:
# create a tensor filled with ones
ones_tensor = tf.ones([4,4], dtype=tf.int8, name=None)
print(ones_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(4, 4), dtype=int8)


In [15]:
# create a tensor of all ones that has the same shape as the input
tensor_ones_like = tf.ones_like(
    tensor_two_d, dtype=tf.int8, name=None
)

print(tensor_ones_like)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]], shape=(4, 3), dtype=int8)


In [16]:
# create a tensor filled with zeros
tensor_zeros = tf.zeros([3,3], dtype=tf.int8)
print(tensor_zeros)

tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int8)


In [17]:
# use the shape() method to get details about the tensor
print(tf.shape(tensor_two_d))

tf.Tensor([4 3], shape=(2,), dtype=int32)


In [18]:
# rank() gives the rank of the tensor
print(tf.rank(tensor_one_d))

tf.Tensor(1, shape=(), dtype=int32)


In [19]:
# size() gives the dtype and the number of elements in the tensor
tensor = tf.constant([
    [[1,1,1],
     [2,2,2]], 

    [[3,3,3],
     [4,4,4]]
])

tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [20]:
'''Random Tensors'''

# generate a tensor from random numbers (random numbers are picked from a normal distribution)

random_tensor = tf.random.normal(
    shape=[3,2], 
    dtype=tf.float32, 
    seed=None,
    mean=0
)

print(random_tensor)

tf.Tensor(
[[-2.9111838  -0.11530113]
 [ 1.2482592  -0.19275557]
 [ 0.40006194  0.7892895 ]], shape=(3, 2), dtype=float32)


In [21]:
# Random tensors from uniform distribution

random_uniform = tf.random.uniform(
    shape=[3,4], 
    minval=0, 
    maxval=10,
    dtype = tf.int32, 
    seed = None
)

print(random_uniform)

tf.Tensor(
[[7 2 9 2]
 [5 6 4 5]
 [3 9 0 8]], shape=(3, 4), dtype=int32)


In [22]:
# set a global seed 
tf.random.set_seed(5)  

print(tf.random.uniform(shape=[3,4], minval=0, maxval=10, dtype = tf.int32, seed = 10))
print(tf.random.uniform(shape=[3,4], minval=0, maxval=10, dtype = tf.int32, seed = 10))
print(tf.random.uniform(shape=[3,4], minval=0, maxval=10, dtype = tf.int32, seed = 10))
print(tf.random.uniform(shape=[3,4], minval=0, maxval=10, dtype = tf.int32, seed = 10))

tf.Tensor(
[[9 3 6 3]
 [5 6 2 8]
 [1 8 9 6]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[9 7 2 7]
 [0 8 0 7]
 [1 9 0 4]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[2 4 2 5]
 [1 3 1 2]
 [6 5 5 1]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[9 0 9 2]
 [6 0 3 9]
 [0 9 8 3]], shape=(3, 4), dtype=int32)


In [23]:
# set a global seed 
tf.random.set_seed(5)  

print(tf.random.uniform(shape=[3,4], minval=0, maxval=10, dtype = tf.int32, seed = 10))
print(tf.random.uniform(shape=[3,4], minval=0, maxval=10, dtype = tf.int32, seed = 10))
print(tf.random.uniform(shape=[3,4], minval=0, maxval=10, dtype = tf.int32, seed = 10))
print(tf.random.uniform(shape=[3,4], minval=0, maxval=10, dtype = tf.int32, seed = 10))

tf.Tensor(
[[9 3 6 3]
 [5 6 2 8]
 [1 8 9 6]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[9 7 2 7]
 [0 8 0 7]
 [1 9 0 4]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[2 4 2 5]
 [1 3 1 2]
 [6 5 5 1]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[9 0 9 2]
 [6 0 3 9]
 [0 9 8 3]], shape=(3, 4), dtype=int32)


In [24]:
# Indexing works the same as python lists