In [1]:
import tensorflow as tf
import random

In [2]:
# absolute value

x = tf.constant([2.25, 0, -3.25, -4.5])
print(x)

print(tf.abs(x))

tf.Tensor([ 2.25  0.   -3.25 -4.5 ], shape=(4,), dtype=float32)
tf.Tensor([2.25 0.   3.25 4.5 ], shape=(4,), dtype=float32)


In [3]:
# convert complex numbers back into real numbers with abs function
complex = tf.constant([0.5518055  +0.7937748j, 0.17062461+0.16515863j, 0.81989443+0.7410884j, 0.7029676 +0.93282485j, 0.40484732+0.05324542j])

print(complex)

print(tf.abs(complex))

tf.Tensor(
[0.5518055 +0.7937748j  0.17062461+0.16515863j 0.81989443+0.7410884j
 0.7029676 +0.93282485j 0.40484732+0.05324542j], shape=(5,), dtype=complex128)
tf.Tensor([0.96673044 0.23746606 1.10518727 1.16804351 0.40833372], shape=(5,), dtype=float64)


In [4]:
# find square root of the tensor
sqrt_tensor = tf.sqrt(x)
print(sqrt_tensor)

tf.Tensor([1.5 0.  nan nan], shape=(4,), dtype=float32)


In [5]:
# exponentiate a tensor wrt to another tensor
x = tf.constant([[1,2,3,6,7,8], [2,3,4,8,6,4]])
y = tf.constant([[2,3,2,3,2,2], [2,2,2,2,2,2]])

print(tf.pow(x, y))

tf.Tensor(
[[  1   8   9 216  49  64]
 [  4   9  16  64  36  16]], shape=(2, 6), dtype=int32)


In [6]:
# arithmetic operations
random.seed(42)
x1 = tf.constant([random.randint(1, 9) for _ in range(6)], dtype=tf.int8)
x2 = tf.constant([random.randint(1, 9) for _ in range(6)], dtype=tf.int8)

print(x1)
print(x2)

print(tf.add(x1, x2))
print(tf.subtract(x1, x2))
print(tf.multiply(x1, x2))
print(tf.divide(x1, x2))


tf.Tensor([2 1 5 4 4 3], shape=(6,), dtype=int8)
tf.Tensor([2 9 2 7 1 1], shape=(6,), dtype=int8)
tf.Tensor([ 4 10  7 11  5  4], shape=(6,), dtype=int8)
tf.Tensor([ 0 -8  3 -3  3  2], shape=(6,), dtype=int8)
tf.Tensor([ 4  9 10 28  4  3], shape=(6,), dtype=int8)
tf.Tensor([1.         0.11111111 2.5        0.5714286  4.         3.        ], shape=(6,), dtype=float32)


In [7]:
a1 = tf.constant([2], dtype=tf.float32)
a2 = tf.constant([0], dtype=tf.float32)

# gives nan
print(tf.divide(a1, a2))

# gives zero instead of nan 
print(tf.math.divide_no_nan(a1, a2))

tf.Tensor([inf], shape=(1,), dtype=float32)
tf.Tensor([0.], shape=(1,), dtype=float32)


In [8]:
'''Broadcasting (atuo-reshaping)'''
# autostretching
b1 = tf.constant([1,5,6,8,9,6,4])
b2 = tf.constant([7])

print(tf.multiply(b1, b2))


# auto fitting
c1 = tf.constant([
                [1,5,6,8,9,6,4,11,12,9],
                [1,2,3,4,5,6,7,8,9,10],
                [1,2,3,4,5,6,7,8,9,10],
                ])
c2 = tf.constant([[7], [5], [3]])

print(tf.multiply(c1,c2))


tf.Tensor([ 7 35 42 56 63 42 28], shape=(7,), dtype=int32)
tf.Tensor(
[[ 7 35 42 56 63 42 28 77 84 63]
 [ 5 10 15 20 25 30 35 40 45 50]
 [ 3  6  9 12 15 18 21 24 27 30]], shape=(3, 10), dtype=int32)


In [9]:
x = tf.constant([
    [2, 30, 30, 3, 6],
    [3, 11, 16, 1, 8], 
    [14, 45, 23, 5, 27]
])
print(x.shape)

y = tf.constant([45, 67, 89, 200, 23])

# returns the position of the maximum element
print(tf.math.argmax(y))

# returns the position of the maximum element, column-wise
print(tf.math.argmax(x))

# change axis = 1, to search row wise
print(tf.math.argmax(x, axis=1))



(3, 5)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([1 2 1], shape=(3,), dtype=int64)


In [10]:
random.seed(42)
tensor_two = tf.constant([
    [random.randint(1,9) for _ in range(9)],
    [random.randint(1,9) for _ in range(9)]
    ])

print(tensor_two)

# reduces the tensor to it's sum of all elements
print(tf.reduce_sum(tensor_two))

# reduces the tensor to it's maximum element
print(tf.reduce_max(tensor_two))

# column-wise via axis=1
print(tf.reduce_sum(x, axis=1))

# similarly for mean, std and more

tf.Tensor(
[[2 1 5 4 4 3 2 9 2]
 [7 1 1 2 4 4 9 1 9]], shape=(2, 9), dtype=int32)
tf.Tensor(70, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([ 71  39 114], shape=(3,), dtype=int32)


In [11]:
# sigmoid function

random.seed(42)

z = tf.constant([random.randint(1,9) for _ in range (9)], dtype=float)
sigmoid = tf.math.sigmoid(z)

print(z)
print(sigmoid)

tf.Tensor([2. 1. 5. 4. 4. 3. 2. 9. 2.], shape=(9,), dtype=float32)
tf.Tensor(
[0.8807971  0.7310586  0.9933072  0.98201376 0.98201376 0.95257413
 0.8807971  0.9998766  0.8807971 ], shape=(9,), dtype=float32)
