In [1]:
import tensorflow as tf

In [2]:
# define random tensors 

tf.random.set_seed(42)

tensor1 = tf.random.uniform(
    shape=[3,3],
    minval = 1,
    maxval = 9, 
    dtype = tf.float16,
)

tensor2 = tf.random.uniform(
    shape=[3,3], 
    minval = 1, 
    maxval = 9, 
    dtype = tf.float16, 
)

print(tensor1)
print(tensor2)

tf.Tensor(
[[1.742 6.82  7.508]
 [1.328 6.97  7.688]
 [1.336 1.523 1.523]], shape=(3, 3), dtype=float16)
tf.Tensor(
[[2.64  7.805 6.65 ]
 [8.33  5.906 8.35 ]
 [7.094 5.36  1.859]], shape=(3, 3), dtype=float16)


In [3]:
# matrix multiplication
print(tf.linalg.matmul(tensor1, tensor2))

print(tensor1 @ tensor2)


tf.Tensor(
[[114.6   94.1   82.5 ]
 [116.06  92.75  81.3 ]
 [ 27.03  27.6   24.44]], shape=(3, 3), dtype=float16)
tf.Tensor(
[[114.6   94.1   82.5 ]
 [116.06  92.75  81.3 ]
 [ 27.03  27.6   24.44]], shape=(3, 3), dtype=float16)


In [4]:
# transpose matrix
print(tf.transpose(tensor1))

tf.Tensor(
[[1.742 1.328 1.336]
 [6.82  6.97  1.523]
 [7.508 7.688 1.523]], shape=(3, 3), dtype=float16)


In [5]:
'''Band Part'''

# Create a sample 4x4 integer tensor
matrix = tf.constant([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print("Original Matrix:")
print(matrix.numpy())
print("-" * 25)


# --- Example 1: Create an upper triangular matrix ---
# Keep the main diagonal (0) and all super-diagonals above it (-1 means all).
# num_lower = 0: Keep zero diagonals below the main one.
# num_upper = -1: Keep all diagonals above the main one.
upper_triangular = tf.linalg.band_part(matrix, num_lower=0, num_upper=-1)

print("Upper Triangular Matrix (num_lower=0, num_upper=-1):")
print(upper_triangular.numpy())
print("-" * 25)


# --- Example 2: Create a lower triangular matrix ---
# Keep the main diagonal (0) and all sub-diagonals below it (-1 means all).
# num_lower = -1: Keep all diagonals below the main one.
# num_upper = 0: Keep zero diagonals above the main one.
lower_triangular = tf.linalg.band_part(matrix, num_lower=-1, num_upper=0)

print("Lower Triangular Matrix (num_lower=-1, num_upper=0):")
print(lower_triangular.numpy())
print("-" * 25)


# --- Example 3: Keep a specific band ---
# Keep the main diagonal, one sub-diagonal, and two super-diagonals.
# num_lower = 1: Keep one diagonal below the main one.
# num_upper = 2: Keep two diagonals above the main one.
banded_matrix = tf.linalg.band_part(matrix, num_lower=1, num_upper=2)

print("Banded Matrix (num_lower=1, num_upper=2):")
print(banded_matrix.numpy())

Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-------------------------
Upper Triangular Matrix (num_lower=0, num_upper=-1):
[[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]
 [ 0  0  0 16]]
-------------------------
Lower Triangular Matrix (num_lower=-1, num_upper=0):
[[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]
 [13 14 15 16]]
-------------------------
Banded Matrix (num_lower=1, num_upper=2):
[[ 1  2  3  0]
 [ 5  6  7  8]
 [ 0 10 11 12]
 [ 0  0 15 16]]


In [7]:
# find determinant
tf.linalg.det(tf.cast(tensor1, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=-0.36821586>

In [8]:
# Find the inverse of the matrix
tf.linalg.inv(tensor1)

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[  2.975 ,  -2.844 ,  -0.3018],
       [-22.39  ,  20.03  ,   9.29  ],
       [ 19.78  , -17.53  ,  -8.375 ]], dtype=float16)>

In [ ]:
# matrix decomposition

# single value decomposition
tf.linalg.svd(tf.cast(tensor2, dtype=tf.float32))

# cholesky decompostion
tf.linalg.cholesky(tf.cast(tensor2, dtype=tf.float32))

2025-09-18 12:04:26.133300: W tensorflow/core/kernels/linalg/cholesky_op.cc:56] Cholesky decomposition was not successful. Eigen::LLT failed with error code 1. Filling lower-triangular output with NaNs.


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[nan,  0.,  0.],
       [nan, nan,  0.],
       [nan, nan, nan]], dtype=float32)>

In [ ]:
# einsum is a function that uses a compact string notation to perform complex tensor operations like matrix multiplication,
transposing, and dot products in a single call.